### ISSUE TITLE
Circular dependency in 0.4.0

### ISSUE THREAD

**Issue by peterwilsoncc** [humanmade/altis-cms-installer#29]
d41fc0716045cfb842fd456eb801f54b5bfa092d introduced a circular dependency, in which altis/cms is required by altis/cms-installer.

Moving the files back to the installer would be helpful.

**Comment by roborourke** [comment]
@peterwilsoncc what's the issue you're seeing?

Moving the files makes it easier for us to maintain things like `wp-config.php` in context rather than making changes to both `altis/cms` and this repo.

The primary reason this repo exists is because `composer-plugin` type packages need to be loaded early but we don't want regular modules loaded before `altis/core`. In future we're looking at having a way for modules to register `composer` commands & hooks without being `composer-plugin` packages themselves.

**Comment by peterwilsoncc** [comment]
> what's the issue you're seeing?

Sorry for the lack of detail.

Setting up a self hosted (Altish) site using a subset of Altis packages throws a fatal during `composer install` as the `/vendor/altis/cms` directory doesn't exist. 

I hit the bug using the following key dependencies:

* altis/core: ^3.0
* altis/cloud ^3.0
* altis/media ^3.0
* altis/cms-installer 0.4
* johnpbloch/wordpress 5.3.x

> Moving the files makes it easier for us to maintain things like `wp-config.php` in context

This makes sense, in which case I'd suggest moving the installer dependency from altis/altis to altis/cms to require open-source users replacing the WordPress version to maintain the files themselves.

**Comment by roborourke** [comment]
Hm, `altis/cms` does require `altis/cms-installer`, `altis/altis` requires `altis/cms`. For the Altish install could you use the `altis/cms` package or was there some reason not to?

**Comment by roborourke** [comment]
I'm not sure this is something we're going to be able to support in this way. It's better to use the `altis/cms` module directly and we'll make sure WP updates are rolled out promptly.
